export const tweetPosts = [
  {
    id: 0,
    name  : 'Dwayne Johnson',
    handlerName : '@The RocK' ,
    organization : ' American actor and former professional wrestler',
    tweetText : '  Johnson wrestled for the WWF for eight years prior to pursuing an acting career. His films have grossed over $3.5 billion in North America and over $10.5 billion worldwide ',
    tweetPic : 'https://talksport.com/wp-content/uploads/sites/5/2021/11/the-rock.jpeg?strip=all&w=960&quality=40',

    tweetCount: 100,
    retweetCount: 100,
    likesCount: 100,
    tweetComment: [],
    isOpen: false,
    inrDcr: false,
    color: "#6A6F74",
    followers: 200,
    followings: 400,
    joinedDate: "22 dec 2022",
    tweets: [
      {
        id: 0,
        tweetText : ' Johnson wrestled for the WWF for eight years prior to pursuing an acting career. His films have grossed over $3.5 billion in North America and over $10.5 billion worldwide ',
        tweetPic : ' https://talksport.com/wp-content/uploads/sites/5/2021/11/the-rock.jpeg?strip=all&w=960&quality=40',
tweetCount: 100,
        retweetCount: 100,
        likesCount: 100,
        viewsCount: "102k",
        TweetReplies: [
          {
            name: "ram",
            handlerName: "ram@gmail.com",
            tweetReplyText: "hello everyone",
            tweetCount: 100,
            retweetCount: 100,
            likesCount: 100,
            viewsCount: "102k",
          },
          {
            name: "sham",
            handlerName: "sham@gmail.com",
            tweetReplyText: "hello everyone",
            tweetCount: 100,
            retweetCount: 100,
            likesCount: 100,
            viewsCount: "102k",
          },
          {
            name: "ram",
            handlerName: "ram@gmail.com",
            tweetReplyText: "hello everyone",
            tweetCount: 100,
            retweetCount: 100,
            likesCount: 100,
            viewsCount: "102k",
          },
          {
            name: "sham",
            handlerName: "sham@gmail.com",
            tweetReplyText: "hello everyone",
            tweetCount: 100,
            retweetCount: 100,
            likesCount: 100,
            viewsCount: "102k",
          },
        ],
      },
      {
        id: 1,
        tweetText : 'Johnson wrestled for the WWF for eight years prior to pursuing an acting career. His films have grossed over $3.5 billion in North America and over $10.5 billion worldwide  ',
        tweetPic : ' https://www.koimoi.com/wp-content/new-galleries/2022/07/dwayne-johnson-wants-to-take-over-wwe-01.jpg',
tweetCount: 100,
        retweetCount: 100,
        likesCount: 100,

        viewsCount: "102k",
        TweetReplies: [
          {
            name: "ram",
            handlerName: "ram@gmail.com",
            tweetReplyText: "hello everyone",
            tweetCount: 100,
            retweetCount: 100,
            likesCount: 100,
            viewsCount: "102k",
          },
          {
            name: "sham",
            handlerName: "sham@gmail.com",
            tweetReplyText: "hello everyone",
            tweetCount: 100,
            retweetCount: 100,
            likesCount: 100,
            viewsCount: "102k",
          },
          {
            name: "ram",
            handlerName: "ram@gmail.com",
            tweetReplyText: "hello everyone",
            tweetCount: 100,
            retweetCount: 100,
            likesCount: 100,
            viewsCount: "102k",
          },
          {
            name: "sham",
            handlerName: "sham@gmail.com",
            tweetReplyText: "hello everyone",
            tweetCount: 100,
            retweetCount: 100,
            likesCount: 100,
            viewsCount: "102k",
          },
        ],
      },
    ],
  },
  {
    id: 1,
    name  : 'wonder Women',
    handlerName : '@Wonderwomen',
    organization : '',
    tweetText : ' Wonder Woman is an Amazon, a race of female warriors in Greek mythology. For the purpose of the Wonder Woman character, it was the Greek gods who gave her her powers.',
    tweetPic : 'https://imagesvc.meredithcorp.io/v3/mm/image?url=https%3A%2F%2Fstatic.onecms.io%2Fwp-content%2Fuploads%2Fsites%2F6%2F2019%2F12%2Fww-2000.jpg' ,
tweetCount: 200,
    retweetCount: 200,
    likesCount: 200,
    tweetComment: [],
    inrDcr: false,
    color: "#6A6F74",
    viewsCount: "10k",
    hastags: ["#wildLife", "#photoGraphy"],
    followers: 200,
    followings: 400,
    joinedDate: "22 dec 2022",
    tweets: [
      {
        tweetText : ' Wonder Woman is an Amazon, a race of female warriors in Greek mythology. For the purpose of the Wonder Woman character, it was the Greek gods who gave her her powers.',

        tweetPic : 'https://imagesvc.meredithcorp.io/v3/mm/image?url=https%3A%2F%2Fstatic.onecms.io%2Fwp-content%2Fuploads%2Fsites%2F6%2F2019%2F12%2Fww-2000.jpg',
        tweetCount: 100,
        retweetCount: 100,
        likesCount: 100,
        viewsCount: "102k",
        TweetReplies: [
          {
            name: "ram",
            handlerName: "ram@gmail.com",
            tweetReplyText: "hello everyone",
            tweetCount: 100,
            retweetCount: 100,
            likesCount: 100,
            viewsCount: "102k",
          },
          {
            name: "sham",
            handlerName: "sham@gmail.com",
            tweetReplyText: "hello everyone",
            tweetCount: 100,
            retweetCount: 100,
            likesCount: 100,
            viewsCount: "102k",
          },
          {
            name: "ram",
            handlerName: "ram@gmail.com",
            tweetReplyText: "hello everyone",
            tweetCount: 100,
            retweetCount: 100,
            likesCount: 100,
            viewsCount: "102k",
          },
          {
            name: "sham",
            handlerName: "sham@gmail.com",
            tweetReplyText: "hello everyone",
            tweetCount: 100,
            retweetCount: 100,
            likesCount: 100,
            viewsCount: "102k",
          },
        ],
      },
      {
        tweetText : ' Wonder Woman is an Amazon, a race of female warriors in Greek mythology. For the purpose of the Wonder Woman character, it was the Greek gods who gave her her powers.',
        tweetPic : 'https://i.pinimg.com/originals/05/65/df/0565df3bca2bf4b5a8f9bca881a8c799.jpg',
tweetCount: 100,
        retweetCount: 100,
        likesCount: 100,
        viewsCount: "102k",
        TweetReplies: [
          {
            name: "ram",
            handlerName: "ram@gmail.com",
            tweetReplyText: "hello everyone",
            tweetCount: 100,
            retweetCount: 100,
            likesCount: 100,
            viewsCount: "102k",
          },
          {
            name: "sham",
            handlerName: "sham@gmail.com",
            tweetReplyText: "hello everyone",
            tweetCount: 100,
            retweetCount: 100,
            likesCount: 100,
            viewsCount: "102k",
          },
          {
            name: "ram",
            handlerName: "ram@gmail.com",
            tweetReplyText: "hello everyone",
            tweetCount: 100,
            retweetCount: 100,
            likesCount: 100,
            viewsCount: "102k",
          },
          {
            name: "sham",
            handlerName: "sham@gmail.com",
            tweetReplyText: "hello everyone",
            tweetCount: 100,
            retweetCount: 100,
            likesCount: 100,
            viewsCount: "102k",
          },
        ],
      },
    ],
  },
  {
    id: 2,
    name : 'AB de Villiers',
    handlerName : '@Mr360*',
    organization : '',
    tweetText : 'South African cricketer ',
    tweetPic : 'https://w0.peakpx.com/wallpaper/392/642/HD-wallpaper-abd-rcb.jpg ',

    tweetCount: 700,
    retweetCount: 700,
    likesCount: 900,
    tweetComment: [],
    inrDcr: false,
    color: "#6A6F74",
    viewsCount: "100k",
    refLink: "https://www.globalwildlife.org/blog/",
    followers: 200,
    followings: 400,
    joinedDate: "22 dec 2022",
    tweets: [
      {
        tweetText : ' proven credentials in all conditions, pressure situations, and across all formats, AB de Villiers is arguably the most complete batsman of his generation. ',
        tweetPic : 'https://qph.cf2.quoracdn.net/main-qimg-e809312da0bd0af0fd1437ef148fb2d5-lq',
tweetCount: 100,
        retweetCount: 100,
        likesCount: 100,
        viewsCount: "102k",
        TweetReplies: [
          {
            name: "ram",
            handlerName: "ram@gmail.com",
            tweetReplyText: "hello everyone",
            tweetCount: 100,
            retweetCount: 100,
            likesCount: 100,
            viewsCount: "102k",
          },
          {
            name: "sham",
            handlerName: "sham@gmail.com",
            tweetReplyText: "hello everyone",
            tweetCount: 100,
            retweetCount: 100,
            likesCount: 100,
            viewsCount: "102k",
          },
          {
            name: "ram",
            handlerName: "ram@gmail.com",
            tweetReplyText: "hello everyone",
            tweetCount: 100,
            retweetCount: 100,
            likesCount: 100,
            viewsCount: "102k",
          },
          {
            name: "sham",
            handlerName: "sham@gmail.com",
            tweetReplyText: "hello everyone",
            tweetCount: 100,
            retweetCount: 100,
            likesCount: 100,
            viewsCount: "102k",
          },
        ],
      },
      {
        tweetText : 'With proven credentials in all conditions, pressure situations, and across all formats, AB de Villiers is arguably the most complete batsman of his generation.',
        tweetPic :'https://m.cricbuzz.com/a/img/v1/600x400/i1/c118941/ab-de-villiers-arrived-in-indore-with-3-fours-and-9-sixes.jpg',
tweetCount: 100,
        retweetCount: 100,
        likesCount: 100,
        viewsCount: "102k",
        TweetReplies: [
          {
            name: "ram",
            handlerName: "ram@gmail.com",
            tweetReplyText: "hello everyone",
            tweetCount: 100,
            retweetCount: 100,
            likesCount: 100,
            viewsCount: "102k",
          },
          {
            name: "sham",
            handlerName: "sham@gmail.com",
            tweetReplyText: "hello everyone",
            tweetCount: 100,
            retweetCount: 100,
            likesCount: 100,
            viewsCount: "102k",
          },
          {
            name: "ram",
            handlerName: "ram@gmail.com",
            tweetReplyText: "hello everyone",
            tweetCount: 100,
            retweetCount: 100,
            likesCount: 100,
            viewsCount: "102k",
          },
          {
            name: "sham",
            handlerName: "sham@gmail.com",
            tweetReplyText: "hello everyone",
            tweetCount: 100,
            retweetCount: 100,
            likesCount: 100,
            viewsCount: "102k",
          },
        ],
      },
    ],
  },
  {
    id: 3,
    name : 'Surya Kumar Yadav',
    handlerName : '@Surya',
    organization : '',
    tweetText : ' टीम इंडिया के विस्फोटक बल्लेबाज सूर्यकुमार यादव ने आज यूपी के मुख्यमंत्री योगी आदित्यनाथ से मुलाकात की.  #Lucknow #UttarPradesh #TeamIndia #INDvsNZ #Trending  ',
    tweetPic : 'https://pbs.twimg.com/media/FntC8KcaAAIb7ox?format=jpg&name=medium',
   


    tweetCount: 400,
    retweetCount: 327,
    likesCount: 90,
    tweetComment: "3",
    tweetComment: [],
    inrDcr: false,
    color: "#6A6F74",
    viewsCount: "7k",
    hastags: ["#sports", "#Winners"],
    followers: 200,
    followings: 400,
    joinedDate: "22 dec 2022",
    tweets: [
      {
        tweetText : ' Suryakumar Ashok Yadav, also known as SKY, is an Indian international cricketer who plays for the Indian cricket team.  ',
        tweetPic : ' https://resources.pulse.icc-cricket.com/ICC/photo/2022/08/15/9891ff6b-2407-4e5e-997c-77419e168b94/GettyImages-1241824431.jpg',
tweetCount: 100,
        retweetCount: 100,
        likesCount: 100,
        viewsCount: "102k",
        TweetReplies: [
          {
            name: "ram",
            handlerName: "ram@gmail.com",
            tweetReplyText: "hello everyone",
            tweetCount: 100,
            retweetCount: 100,
            likesCount: 100,
            viewsCount: "102k",
          },
          {
            name: "sham",
            handlerName: "sham@gmail.com",
            tweetReplyText: "hello everyone",
            tweetCount: 100,
            retweetCount: 100,
            likesCount: 100,
            viewsCount: "102k",
          },
          {
            name: "ram",
            handlerName: "ram@gmail.com",
            tweetReplyText: "hello everyone",
            tweetCount: 100,
            retweetCount: 100,
            likesCount: 100,
            viewsCount: "102k",
          },
          {
            name: "sham",
            handlerName: "sham@gmail.com",
            tweetReplyText: "hello everyone",
            tweetCount: 100,
            retweetCount: 100,
            likesCount: 100,
            viewsCount: "102k",
          },
        ],
      },
      {
        tweetText : ' Suryakumar Ashok Yadav, also known as SKY, is an Indian international cricketer who plays for the Indian cricket team.  ',
                tweetPic : ' https://p.imgci.com/db/PICTURES/CMS/343500/343568.jpg',
 tweetCount: 100,
        retweetCount: 100,
        likesCount: 100,
        viewsCount: "102k",
        TweetReplies: [
          {
            name: "ram",
            handlerName: "ram@gmail.com",
            tweetReplyText: "hello everyone",
            tweetCount: 100,
            retweetCount: 100,
            likesCount: 100,
            viewsCount: "102k",
          },
          {
            name: "sham",
            handlerName: "sham@gmail.com",
            tweetReplyText: "hello everyone",
            tweetCount: 100,
            retweetCount: 100,
            likesCount: 100,
            viewsCount: "102k",
          },
          {
            name: "ram",
            handlerName: "ram@gmail.com",
            tweetReplyText: "hello everyone",
            tweetCount: 100,
            retweetCount: 100,
            likesCount: 100,
            viewsCount: "102k",
          },
          {
            name: "sham",
            handlerName: "sham@gmail.com",
            tweetReplyText: "hello everyone",
            tweetCount: 100,
            retweetCount: 100,
            likesCount: 100,
            viewsCount: "102k",
          },
        ],
      },
    ],
  },
  {
    id: 4,
    name : 'Motu-paTlu',
    handlerName : '@MotuPatlu',
    organization : '',
    tweetText : ' Best friends Motu and Patlu live in Furfuri Nagar and always fall into trouble. To get out of those problems, often due to Motus clumsy actions, they eventually get help from their other friends. ',
    tweetPic : ' http://cdn.shopify.com/s/files/1/0527/0795/0750/collections/Motu-patlu.jpg?v=1659161477',

    tweetCount: 650,
    retweetCount: 699,
    likesCount: 900,
    tweetComment: [],
    inrDcr: false,
    color: "#6A6F74",
    viewsCount: "17k",
    hastags: ["#HockeyLover", "#Hockey", "#Team India"],
    followers: 200,
    followings: 400,
    joinedDate: "22 dec 2022",
    tweets: [
      {
        tweetText : ' Best friends Motu and Patlu live in Furfuri Nagar and always fall into trouble. To get out of those problems, often due to Motus clumsy actions, they eventually get help from their other friends. ',
        tweetPic : 'https://m.media-amazon.com/images/M/MV5BODY4Y2UyODUtYjkzNC00NmZlLWEzNWYtMTAxYmIzNGVlYmVkXkEyXkFqcGdeQXVyODAzNzAwOTU@.V1.jpg',

        tweetCount: 100,
        retweetCount: 100,
        likesCount: 100,
        viewsCount: "102k",
        TweetReplies: [
          {
            name: "ram",
            handlerName: "ram@gmail.com",
            tweetReplyText: "hello everyone",
            tweetCount: 100,
            retweetCount: 100,
            likesCount: 100,
            viewsCount: "102k",
          },
          {
            name: "sham",
            handlerName: "sham@gmail.com",
            tweetReplyText: "hello everyone",
            tweetCount: 100,
            retweetCount: 100,
            likesCount: 100,
            viewsCount: "102k",
          },
          {
            name: "ram",
            handlerName: "ram@gmail.com",
            tweetReplyText: "hello everyone",
            tweetCount: 100,
            retweetCount: 100,
            likesCount: 100,
            viewsCount: "102k",
          },
          {
            name: "sham",
            handlerName: "sham@gmail.com",
            tweetReplyText: "hello everyone",
            tweetCount: 100,
            retweetCount: 100,
            likesCount: 100,
            viewsCount: "102k",
          },
        ],
      },
      {
        tweetText : ' Best friends Motu and Patlu live in Furfuri Nagar and always fall into trouble. To get out of those problems, often due to Motus clumsy actions, they eventually get help from their other friends.',
        tweetPic : 'https://static.toiimg.com/thumb/resizemode-4,width-1200,height-900,msid-54752036/54752036.jpg',

        tweetCount: 100,
        retweetCount: 100,
        likesCount: 100,
        viewsCount: "102k",
        TweetReplies: [
          {
            name: "ram",
            handlerName: "ram@gmail.com",
            tweetReplyText: "hello everyone",
            tweetCount: 100,
            retweetCount: 100,
            likesCount: 100,
            viewsCount: "102k",
          },
          {
            name: "sham",
            handlerName: "sham@gmail.com",
            tweetReplyText: "hello everyone",
            tweetCount: 100,
            retweetCount: 100,
            likesCount: 100,
            viewsCount: "102k",
          },
          {
            name: "ram",
            handlerName: "ram@gmail.com",
            tweetReplyText: "hello everyone",
            tweetCount: 100,
            retweetCount: 100,
            likesCount: 100,
            viewsCount: "102k",
          },
          {
            name: "sham",
            handlerName: "sham@gmail.com",
            tweetReplyText: "hello everyone",
            tweetCount: 100,
            retweetCount: 100,
            likesCount: 100,
            viewsCount: "102k",
          },
        ],
      },
    ],
  },
  {
    id: 5,
    name : 'Narendra Modi',
    handlerName : '@MODIJI-bjp',
    organization : 'Prime Minister of India',
    tweetText : `Narendra Damodardas Modi is an Indian politician serving as the 14th and current Prime Minister of India since 2014.  `,
    tweetPic : ' https://i0.wp.com/www.opindia.com/wp-content/uploads/2022/10/PM-Modi-Image-007-13102022.jpg?fit=1189%2C689&ssl=1',

    tweetCount: 650,
    retweetCount: 699,
    likesCount: 900,
    tweetComment: [],
    inrDcr: false,
    color: "#6A6F74",
    viewsCount: "17k",
    followers: 200,
    followings: 400,
    joinedDate: "22 dec 2022",
    tweets: [
      {
        tweetText : '  Narendra Damodardas Modi is an Indian politician serving as the 14th and current Prime Minister of India since 2014.',
        tweetPic : ' https://www.thestatesman.com/wp-content/uploads/2022/09/03_Merged.jpg',
tweetCount: 100,
        retweetCount: 100,
        likesCount: 100,
        viewsCount: "102k",
        TweetReplies: [
          {
            name: "ram",
            handlerName: "ram@gmail.com",
            tweetReplyText: "hello everyone",
            tweetCount: 100,
            retweetCount: 100,
            likesCount: 100,
            viewsCount: "102k",
          },
          {
            name: "sham",
            handlerName: "sham@gmail.com",
            tweetReplyText: "hello everyone",
            tweetCount: 100,
            retweetCount: 100,
            likesCount: 100,
            viewsCount: "102k",
          },
          {
            name: "ram",
            handlerName: "ram@gmail.com",
            tweetReplyText: "hello everyone",
            tweetCount: 100,
            retweetCount: 100,
            likesCount: 100,
            viewsCount: "102k",
          },
          {
            name: "sham",
            handlerName: "sham@gmail.com",
            tweetReplyText: "hello everyone",
            tweetCount: 100,
            retweetCount: 100,
            likesCount: 100,
            viewsCount: "102k",
          },
        ],
      },
      {
        tweetText : ' Modi was the Chief Minister of Gujarat from 2001 to 2014 and is the Member of Parliament from Varanasi.  ',
        tweetPic : ' https://upload.wikimedia.org/wikipedia/commons/8/80/PM_at_First_Meeting_of_Central_Asia_Summit.jpg',
tweetCount: 100,
        retweetCount: 100,
        likesCount: 100,
        viewsCount: "102k",
        TweetReplies: [
          {
            name: "ram",
            handlerName: "ram@gmail.com",
            tweetReplyText: "hello everyone",
            tweetCount: 100,
            retweetCount: 100,
            likesCount: 100,
            viewsCount: "102k",
          },
          {
            name: "sham",
            handlerName: "sham@gmail.com",
            tweetReplyText: "hello everyone",
            tweetCount: 100,
            retweetCount: 100,
            likesCount: 100,
            viewsCount: "102k",
          },
          {
            name: "ram",
            handlerName: "ram@gmail.com",
            tweetReplyText: "hello everyone",
            tweetCount: 100,
            retweetCount: 100,
            likesCount: 100,
            viewsCount: "102k",
          },
          {
            name: "sham",
            handlerName: "sham@gmail.com",
            tweetReplyText: "hello everyone",
            tweetCount: 100,
            retweetCount: 100,
            likesCount: 100,
            viewsCount: "102k",
          },
        ],
      },
    ],
  },
  {
    id: 6,
    name : 'Virat kohli',
    handlerName : '@KING kohli',
    organization : 'Indian cricketer        ',
    tweetText : `Virat Kohli is an Indian international cricketer and former captain of the Indian national team. Widely regarded as one of the greatest batsmen of all time, `,
    tweetPic : 'https://akm-img-a-in.tosshub.com/aajtak/images/photo_gallery/202205/kohli_virat.jpg ',

    tweetCount: 100,
    retweetCount: 509,
    likesCount: 450,
    inrDcr: false,
    color: "#6A6F74",
    viewsCount: "79k",
    hastags: ["#Freedom Fighter", "#India"],
    followers: 200,
    followings: 400,
    joinedDate: "22 dec 2022",
    tweets: [
      {
        tweetText : ' Virat Kohli is an Indian international cricketer and former captain of the Indian national team. Widely regarded as one of the greatest batsmen of all time, ',
        tweetPic : 'https://im.rediff.com/cricket/2022/may/05kohli1.JPG',
tweetCount: 100,
        retweetCount: 100,
        likesCount: 100,
        viewsCount: "102k",
        TweetReplies: [
          {
            name: "",
            handlerName: "",
            tweetReplyText: "",
          },
          {
            name: "",
            handlerName: "",
            tweetReplyText: "",
          },
        ],
      },
      {
        tweetText : ' Virat Kohli is an Indian international cricketer and former captain of the Indian national team. Widely regarded as one of the greatest batsmen of all time,',
        tweetPic : 'https://images.news18.com/ibnlive/uploads/2022/04/virat-kohli-ipl-2022.jpg',
tweetCount: 100,
        retweetCount: 100,
        likesCount: 100,
        viewsCount: "102k",
        TweetReplies: [
          {
            name: "",
            handlerName: "",
            tweetReplyText: "",
          },
          {
            name: "",
            handlerName: "",
            tweetReplyText: "",
          },
        ],
      },
    ],
  },
  {
    id: 7,
    name : ' Aishwarya Rai Bachchan',
    handlerName : '@aishwarya',
    organization : 'Indian actress        ',
    tweetText : ` Aishwarya Rai Bachchan is an Indian actress who is primarily known for her work in Hindi and Tamil films. The winner of the Miss World 1994 pageant, she has established herself as one of the most popular`,
    tweetPic : 'https://www.whoa.in/download/aishwarya-rai-smile-shining-eyes-hd--wallpaper ',

    tweetCount: 100,
    retweetCount: 509,
    likesCount: 450,
    inrDcr: false,
    color: "#6A6F74",
    viewsCount: "79k",
    refLink: "https://twitter.com/aishwarya",
    hastags: ["#Electronics", "#iphone"],
    followers: 200,
    followings: 400,
    joinedDate: "22 dec 2022",
    tweets: [
      {
        tweetText : ' Aishwarya Rai Bachchan is an Indian actress who is primarily known for her work in Hindi and Tamil films. The winner of the Miss World 1994 pageant, she has established herself as one of the most popular ',
        tweetPic : ' https://www.filmibeat.com/wimg/desktop/2019/07/aishwarya-rai-bachchan_16.jpg',
tweetCount: 100,
        retweetCount: 100,
        likesCount: 100,
        viewsCount: "102k",
        TweetReplies: [
          {
            name: "",
            handlerName: "",
            tweetReplyText: "",
          },
          {
            name: "",
            handlerName: "",
            tweetReplyText: "",
          },
        ],
      },
      {
        tweetText : ' Aishwarya Rai Bachchan is an Indian actress who is primarily known for her work in Hindi and Tamil films. The winner of the Miss World 1994 pageant, she has established herself as one of the most popular ',
        tweetPic : ' https://wallpaperaccess.com/full/1279803.jpg',
tweetCount: 100,
        retweetCount: 100,
        likesCount: 100,
        viewsCount: "102k",
        TweetReplies: [
          {
            name: "",
            handlerName: "",
            tweetReplyText: "",
          },
          {
            name: "",
            handlerName: "",
            tweetReplyText: "",
          },
        ],
      },
    ],
  },
  {
    id: 8,
    name : 'Shah Rukh khan',
    handlerName : '@SRk',
    organization : 'Actor' ,
    tweetText : ' Shah Rukh Khan has unveiled new posters of Pathaan which include solo posters of him, Deepika Padukone and John Abraham. ',
    tweetPic : ' https://pbs.twimg.com/media/E1-zMFKUYAY-dFP.jpg',
tweetCount: 10,
    retweetCount: 50,
    likesCount: 40,
    inrDcr: false,
    color: "#6A6F74",
    viewsCount: "9k",
    hastags: ["#bcm112", "#students", "#education", "#allGovernmets"],
    refLink: "https://twitter.com/ippittipapitti",
    followers: 200,
    followings: 400,
    joinedDate: "22 dec 2022",
    tweets: [
      {
        tweetText : ' Shah Rukh Khan, also known by the initialism SRK, is an Indian actor and film producer who works in Hindi films.  ',
        tweetPic : ' https://img.mensxp.com/media/content/2022/Aug/Header-Image_BCCL_62e91b2d4c4a5.jpeg',
tweetCount: 100,
        retweetCount: 100,
        likesCount: 100,
        viewsCount: "102k",
        TweetReplies: [
          {
            name: "",
            handlerName: "",
            tweetReplyText: "",
          },
          {
            name: "",
            handlerName: "",
            tweetReplyText: "",
          },
        ],
      },
      {
        tweetText : ' Shah Rukh Khan, also known by the initialism SRK, is an Indian actor and film producer who works in Hindi films.  ',
        tweetPic : 'https://images.news18.com/ibnlive/uploads/2021/11/shah-rukh-khan-2-1.jpg ',
tweetCount: 100,
        retweetCount: 100,
        likesCount: 100,
        viewsCount: "102k",
        TweetReplies: [
          {
            name: "",
            handlerName: "",
            tweetReplyText: "",
          },
          {
            name: "",
            handlerName: "",
            tweetReplyText: "",
          },
        ],
      },
    ],
  },
  {
    id: 9,
    name : 'MS Dhoni',
    handlerName : '@THALA',
    organization : 'Indian cricketer        ',
    tweetText : 'Mahendra Singh Dhoni, commonly known as MS Dhoni, is a former Indian cricketer and captain of the Indian national team in limited-overs formats from 2007 to 2017, and in Test cricket from 2008 to 2014. ',
    tweetPic : ' https://akm-img-a-in.tosshub.com/indiatoday/images/story/202211/untitled-1_0-one_one.jpg?VersionId=2UvgyBhEFLLMzztCbeFTTShGb9c33ddU',
tweetCount: 10,
    retweetCount: 50,
    likesCount: 40,
    inrDcr: false,
    color: "#6A6F74",
    viewsCount: "9k",
    hastags: ["#Education", "#Rajasthan"],
    refLink: "https://dainik-b.in/ekPIEaD5Jwb",
    followers: 200,
    followings: 400,
    joinedDate: "22 dec 2022",
    tweets: [
      {
        tweetText : ' He is also the current captain of Chennai Super Kings in the Indian Premier League. ',
        tweetPic : 'https://im.rediff.com/cricket/2020/sep/19msd-toss.jpg ',
tweetCount: 100,
        retweetCount: 100,
        likesCount: 100,
        viewsCount: "102k",
        TweetReplies: [
          {
            name: "",
            handlerName: "",
            tweetReplyText: "",
          },
          {
            name: "",
            handlerName: "",
            tweetReplyText: "",
          },
        ],
      },
      {
        tweetText : ' He is also the current captain of Chennai Super Kings in the Indian Premier League. ',
        tweetPic : 'https://c.ndtvimg.com/2021-11/o66r0bb8_ms-dhoni-ipl_625x300_20_November_21.jpg?im=FeatureCrop,algorithm=dnn,width=806,height=605 ',
tweetCount: 100,
        retweetCount: 100,
        likesCount: 100,
        viewsCount: "102k",
        TweetReplies: [
          {
            name: "",
            handlerName: "",
            tweetReplyText: "",
          },
          {
            name: "",
            handlerName: "",
            tweetReplyText: "",
          },
        ],
      },
    ],
  },
  {
    id: 10,
    name: "Madhya Pradesh Tourism",
    handlerName: "@MPTourism",
    organization: "Mp tourism",
    tweetText:
      "If you are a nature-lover who loves to spend time in the jungle and adores the mighty #bigcats, plan a jungle safari in the #HeartofIndia. Wander through the lush green forests and keep your cameras handy!",
    tweetPic:
      "https://www.tourmyindia.com/states/madhyapradesh/image/mp-tourism.webp",
    retweetCount: 50,
    likesCount: 40,
    inrDcr: false,
    color: "#6A6F74",
    viewsCount: "9k",
    hastags: ["#BIGcat", "#HeartofIndia"],
    refLink: "https://www.mptigerfoundation.org/news-corner/blog",
    followers: 200,
    followings: 400,
    joinedDate: "22 dec 2022",
    tweets: [
      {
        tweetText:
          "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industrys standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. ",
        tweetPic:
          "https://lh3.googleusercontent.com/8ygpNx4Er1H9LmB-D8W7cBi-qsvcDSDlWw2CVIk5bHFM77q6a46V0GNxSzopAUtvLKIApDTW7RKnrJ7m7Yp4obN1s23V3dRMrYLwvz5GJc_gu1N-M8tGkyhFYGf40nwZCg7jbgGa1g=w1920-h1080",
        tweetCount: 100,
        retweetCount: 100,
        likesCount: 100,
        viewsCount: "102k",
        TweetReplies: [
          {
            name: "",
            handlerName: "",
            tweetReplyText: "",
          },
          {
            name: "",
            handlerName: "",
            tweetReplyText: "",
          },
        ],
      },
      {
        tweetText:
          "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industrys standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. ",
        tweetPic:
          "https://lh3.googleusercontent.com/8ygpNx4Er1H9LmB-D8W7cBi-qsvcDSDlWw2CVIk5bHFM77q6a46V0GNxSzopAUtvLKIApDTW7RKnrJ7m7Yp4obN1s23V3dRMrYLwvz5GJc_gu1N-M8tGkyhFYGf40nwZCg7jbgGa1g=w1920-h1080",
        tweetCount: 100,
        retweetCount: 100,
        likesCount: 100,
        viewsCount: "102k",
        TweetReplies: [
          {
            name: "",
            handlerName: "",
            tweetReplyText: "",
          },
          {
            name: "",
            handlerName: "",
            tweetReplyText: "",
          },
        ],
      },
    ],
  },
];
